/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GekoButton {
    }
    interface GekoFlex {
        "direction": 'column' | 'row';
    }
}
declare global {
    interface HTMLGekoButtonElement extends Components.GekoButton, HTMLStencilElement {
    }
    var HTMLGekoButtonElement: {
        prototype: HTMLGekoButtonElement;
        new (): HTMLGekoButtonElement;
    };
    interface HTMLGekoFlexElement extends Components.GekoFlex, HTMLStencilElement {
    }
    var HTMLGekoFlexElement: {
        prototype: HTMLGekoFlexElement;
        new (): HTMLGekoFlexElement;
    };
    interface HTMLElementTagNameMap {
        "geko-button": HTMLGekoButtonElement;
        "geko-flex": HTMLGekoFlexElement;
    }
}
declare namespace LocalJSX {
    interface GekoButton {
    }
    interface GekoFlex {
        "direction"?: 'column' | 'row';
    }
    interface IntrinsicElements {
        "geko-button": GekoButton;
        "geko-flex": GekoFlex;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "geko-button": LocalJSX.GekoButton & JSXBase.HTMLAttributes<HTMLGekoButtonElement>;
            "geko-flex": LocalJSX.GekoFlex & JSXBase.HTMLAttributes<HTMLGekoFlexElement>;
        }
    }
}
